In [28]:
#importer vos librairies 
import pandas as pd 
import numpy as np 
from sklearn import linear_model 
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.model_selection import ShuffleSplit
from sklearn.model_selection import *

In [6]:
#charger les données 
#price_availability.csv
#listings_final.csv
#attention aux valeurs manquantes !!

df_PA= pd.read_csv('price_availability.csv', sep=';')
df_LF= pd.read_csv('listings_final.csv', sep=';')

In [42]:
df_PA= df_PA.groupby("listing_id").mean()

In [43]:
df = pd.merge(df_PA,df_LF, on=['listing_id'])
df

,listing_id,available,local_price,min_nights,Unnamed: 0,name,type,city,neighborhood,latitude,...,beds,bedrooms,bathrooms,is_rebookable,is_new_listing,is_fully_refundable,is_host_highly_rated,is_business_travel_ready,pricing_weekly_factor,pricing_monthly_factor
0,56093,0.000000,170.000000,4.000000,12,Beau duplex dans le Marais,entire_home,Paris,3e arrondissement,48.867284,...,2,1,1.0,False,False,True,True,False,0.88,1.0
1,57207,0.482940,49.952756,2.000000,13,Belle Chambre pour court,private_room,Paris,Vaugirard,48.846184,...,1,1,1.0,False,False,True,False,False,0.87,1.0
2,114543,0.140260,107.374026,3.716883,19,Charming 1bdr 55m² - Eiffel Tower,entire_home,Paris,NaN,48.849530,...,1,1,1.0,False,False,True,True,False,0.90,0.9
3,149534,0.554974,169.000000,3.000000,9,GREAT WARM FULL APT LE HAUT MARAIS,entire_home,Paris,NaN,48.866360,...,2,1,1.0,False,False,True,True,False,1.00,0.4
4,164255,0.100580,75.876209,3.841393,28,Perfect place in Le Marais - Paris,entire_home,Paris,3e arrondissement,48.861398,...,2,1,1.0,False,False,True,False,False,1.00,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
994,28684174,0.785156,725.175781,1.046875,662,Chambre familiale vue jardin avec petit-déjeun...,private_room,Paris,Ternes,48.879223,...,0,1,1.0,False,True,True,False,False,1.00,1.0
995,28709644,0.954286,475.000000,6.000000,745,LORD BYRON-SPACE& STYLE IN 8TH EME,entire_home,Paris,Champs-Elysées,48.872202,...,2,1,1.0,False,True,True,False,False,1.00,1.0
996,28751412,0.521053,117.000000,1.000000,88,Malesherbes Monceau Monsen,entire_home,Paris,Monceau,48.880923,...,1,0,1.0,False,True,True,False,False,1.00,1.0
997,28774896,0.840506,156.397468,1.000000,159,5 min to invalides and 10 min to eiffel tower,entire_home,Paris,Invalides - Ecole Militaire,48.852915,...,1,1,1.0,False,True,True,False,False,1.00,1.0
998,28792796,0.639098,49.184211,5.000000,998,Appartement 3 chambres madeleine.,entire_home,Paris,Madeleine - Vendôme,48.870109,...,4,2,1.5,False,True,True,False,False,1.00,1.0

In [44]:
y = np.array(df.local_price)
X = np.array([df.person_capacity,df.bedrooms, df.bathrooms])
X.shape

(3, 999)

In [45]:
X=X.reshape((999,3))
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=42)

In [ ]:
#utiliser la méthode split de sklearn en splitant avec un alpha=30 et un random state=42 
#rs = ShuffleSplit(random_state=42)rs.get_n_splits(y)afficher la shape de vos données